server:
  servlet:
    contextPath: /
  port: 19999
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 20
spring:
  mail:
    host: smtp.qq.com
    username: xuxiaoby@qq.com
    password: iggtelienmqibbid
    default-encoding: UTF-8
  shardingsphere:
    datasource:
      names: tanglingyu
      #tanglingyu 配置
      tanglingyu:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: sdm619094438
        password: Yichen360
        jdbc-url: jdbc:mysql://sdm619094438.my3w.com:3306/sdm619094438_db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT
    sharding:
      tables:
        t_order:
          actual-data-nodes: tanglingyu.t_order_$->{0..2}
          table-strategy:
            standard:
              sharding-column: id
              #algorithm-expression: t_order$->{id % 3}
              precise-algorithm-class-name: com.search.bean.TableShardingAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      sql:
        show: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      clusterNodes: 127.0.0.1:9300
elasticsearch:
  host: 127.0.0.1
  port: 9200
  article:
    index: articleindex

mybatis:
  mapper-locations: classpath*:mapper/*.xml
pagehelper:
  helperDialect: mysql
  pageSizeZero: false
  reasonable: true #pageSize=0
  supportMethodsArguments: true
workId: 1
dataCenter: 1
EMAIL_REGEXP: "^(\\s)*|^([a-z0-9A-Z]|-|\\.|_|!)+@[a-z0-9A-Z]+\\.[a-z0-9A-Z]{2,}$"

logging:
  config: classpath:config/spring/logback.xml
  level:
    com.search: debug # 开发环境调试
    com.baomidou: debug # 开发环境调试
