server:
  servlet:
    contextPath: /
  port: 19999
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 20
spring:
  mail:
    host: smtp.qq.com
    username: xuxiaoby@qq.com
    password: iggtelienmqibbid
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            trust: smtp.qq.com
        socketFactory:
          class: javax.net.ssl.SSLSocketFactory
          port: 465
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    username: sdm619094438
    password: Yichen360
    url: jdbc:mysql://sdm619094438.my3w.com:3306/sdm619094438_db?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
pagehelper:
  helperDialect: mysql
  pageSizeZero: false
  reasonable: true #pageSize=0
  supportMethodsArguments: true
workId: 1
dataCenter: 1
EMAIL_REGEXP: "^(\\s)*|^([a-z0-9A-Z]|-|\\.|_|!)+@[a-z0-9A-Z]+\\.[a-z0-9A-Z]{2,}$"

logging:
  config: classpath:config/spring/logback.xml
  level:
    com.search: debug # 开发环境调试
    com.baomidou: debug # 开发环境调试
