server:
  port: 19999
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 4
      worker: 20
    servlet:
      context-path: /

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/shopping?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
pagehelper:
  helperDialect:
  reasonable: true
  pagehelper:
    supportMethodsArguments: true
    pageSizeZero: false #pageSize=0
workId: 1
dataCenter: 1
EMAIL_REGEXP: ^(\\s)*|^([a-z0-9A-Z]|-|\\.|_|!)+@[a-z0-9A-Z]+\\.[a-z0-9A-Z]{2,}$

logging:
  config: classpath:config/spring/logback.xml
  level:
    com.search: debug # 开发环境调试
    org.mybatis: debug # 开发环境调试
